### ISSUE TITLE
Error: Map container is already initialized.

### ISSUE THREAD

**Issue by idris11** [joblocal/vue-mapfit#5]
I have created 2 components mapfit in same file, then error display 'Error: Map container is already initialized'. How to resolve this issue?

**Comment by I2olanD** [comment]
@idris11 thanks for your submit! I opened a PR. Should be fixed soon :) #6

**Comment by I2olanD** [comment]
Resolved with #6

**Comment by idris11** [comment]
thank's @I2olanD
